name: Deploy Backend to Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Build project
        run: npm run build
        working-directory: ./backend

      - name: Deploy via rsync + ssh
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SERVER_SSH_PORT }}
          SOURCE: "backend/"
          TARGET: "/var/www/aquanet/backend"
          EXCLUDE: ".env node_modules .git .github"
          SCRIPT_AFTER: |
            cd /var/www/aquanet/backend
            npm install
            npm run build
            pm2 restart aquanet-backend || pm2 start dist/main.js --name aquanet-backend
